SELECT * FROM project_data_analyist.mytable;

-- 1 What is the total revenue generated by male vs. female customers? 
select gender , sum(purchase_amount) as revenu from project_data_analyist.mytable group by gender ;

-- 2  Which customers used a discount but still spent more than the average purchase amount? 
select customer_id , purchase_amount from project_data_analyist.mytable where discount_applied ="Yes" and purchase_amount>= (select avg(purchase_amount) from project_data_analyist.mytable);

 -- 3  Which are the top 5 products with the highest average review rating?
select item_purchased , avg(review_rating) as "average product rating" from project_data_analyist.mytable group by item_purchased order by avg(review_rating) desc limit 5;

--  4    Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type , avg(purchase_amount) from  project_data_analyist.mytable where shipping_type in ("Standard" , "Express") group by shipping_type;

-- 5  Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status , count(customer_id) as total_customer , avg(purchase_amount) as avg_amount , sum(purchase_amount) as total_amount from project_data_analyist.mytable group by subscription_status order by  total_amount , avg_amount desc ;

-- 6  Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased , 100*sum(case when discount_applied = "Yes" then 1 else 0 end )/count(*) as discount_rate from project_data_analyist.mytable group by item_purchased order by discount_rate desc limit 5;

-- 7  Segment customers into New, Returning, and Loyal based on their total  number of previous purchases, and show the count of each segment.
 with customer_type as ( select customer_id , previous_purchases , case when previous_purchases = 1 then "New" when previous_purchases between 2 and 10 then "Returing" else "Loyal" end as customer_segement from project_data_analyist.mytable ) select customer_segement , count(*) as "Number of Customers" from customer_type group by customer_segement ;

 --  8   What are the top 3 most purchased products within each category? 
 with item_counts as (select category , item_purchased , count(customer_id) as total_orders, row_number() over(partition by category order by count(customer_id) desc) as item_rank from project_data_analyist.mytable group by category , item_purchased) select item_rank , category , item_purchased , total_orders from item_counts where item_rank<=3 ;
 
 --  9  Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status , count(customer_id) as repeat_buyers from project_data_analyist.mytable where previous_purchases>5 group by subscription_status;
 
 -- 10   What is the revenue contribution of each age group? 
 select age_group , sum(purchase_amount) as total_revenue from project_data_analyist.mytable group by age_group order by total_revenue desc ;